language: rust
rust:
  - stable
  - beta
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add clippy
script:
  - cargo build --verbose --all
  - cargo clippy --all-targets --all-features
  - cargo test --verbose --all
